### ISSUE TITLE
Write up user stories for Custom Tickets

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/Product#2]
### Description
Complete the document https://coda.io/d/3D-Repo-Features_d5c0Qp25r6f/Custom-Tickets_suLxE#_lun2Z

### Sub-tasks
- [ ] Scope A - Integrate Groups into Issues & Risks
- [ ] Scope B - Allow manifest configuration for Issues
- [ ] Scope C - Add additional fields types to issues
- [ ] Scope D - Customise Pin output
- [ ] Scope E - Include External Data
