### ISSUE TITLE
Get Logic App Custom Connector working

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/Product#3]
### Description
Once Microsoft have responded with the details of how to create the chunking working, we need to create a full set of Swagger API docs for Logic Apps

### Sub-tasks
- [ ] Get the chunking connection working
- [ ] Write Issues API Calls
- [ ] Write Risks API Calls
- [ ] Write Groups API Calls
- [ ] Write Metadata API Calls

### Links
[Link to connector on Azure](https://portal.azure.com/#@3drepo.org/resource/subscriptions/e5f72de0-25cb-4bdd-8e9c-a897d8ff91cd/resourceGroups/PowerBI/providers/Microsoft.Logic/workflows/2489ChunkingTestCustomConnector/logicApp)
